### PR TITLE
Add support for Subnautica

### PR DESCRIPTION
**Pull request by dekart811**
This will add basic support for Subnautica. I have only tested it with the Steam version, but I guess the Epic Store version should work too.

### CODE REVIEW

**Comment by LostDragonist** [comment]
@dekart811 What is doorstep_config.ini supposed to be?  This doesn't appear to be part of a vanilla Subnautica install and Google isn't helping me out.  Without this file in place, MO is going to throw an error.

**Comment by LostDragonist** [comment]
Oh, doorstop not doorstep.  It's a file from QModManager.  That means the user has to have QModManager installed before the MO2 GUI will open.  Hmm.

Does defining doorstop_config.ini in the game plugin actually add any wanted functionality?  That's normally for stuff that would be different between different profiles.  I'm not entirely sure that'd work in this case.

**Comment by Qudix** [comment]
Doorstop is a managed dll loader for unity games. It's not specific to QModManager.
https://github.com/NeighTools/UnityDoorstop

**Comment by dekart811** [comment]
@LostDragonist you can't install any mods for Subnautica without having QModManager installed first.

**Comment by LostDragonist** [comment]
The problem is how do we tell the user that if MO doesn't launch.  Though this seems to be a more pervasive problem than just this plugin so I guess it'll have to be fixed more comprehensively later on. /shrug.  This is consistent with how other plugins are being used right now so works for me.

**Pull request merged**
