### PR TITLE
Add support for Daggerfall Unity.

### PR DESCRIPTION
**Pull request by jimfcarroll**
This adds support for Daggerfall Unity.  It has rudimentary support for determining if a mod is packaged correctly.

### CODE REVIEW

**Comment by Holt59** [comment]
Daggerfall Unity does not have plugin files in the data folder (regarding the mod-data checker)?

**Comment by jimfcarroll** [comment]
@Holt59 not sure what you mean. Looks like the linter failed. I didn't know there was a particular code format required. Anyone have code format files for VSCode? I can reformat.

**Comment by Holt59** [comment]
> 
> 
> @Holt59 not sure what you mean. Looks like the linter failed. I didn't know there was a particular code format required. Anyone have code format files for VSCode? I can reformat.

I mean that your mod-checker does not accept mods containing files directly in the data folder, similar to `.esp` or `.esm` in modern Besthesda games, so I'm wondering if it's something you missed or if Daggefall Unity does not actually have such things.

For VS Code, you need something like this (you need a Python virtual env with `black` installed):

```json
{
    "editor.insertSpaces": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "python.formatting.provider": "black",
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        }
    },
}
```

You might also want to check for linters error with `flake8` and `mypy`. You can install `tox` locally and run `tox` to run check locally on your machine.

**Comment by jimfcarroll** [comment]
DFU's mods go in subdirectories of `%GAME_PATH%/DaggerfallUnity_Data/StreamingAssets` and not directly in that folder. Usually the subdirectory is "Mods" and that will have `*.dfmod` files but a "mod" can use any of the other directories listed also.

**Comment by jimfcarroll** [comment]
FWIW, I used this to install 50-60 mods about 1/2 of which were incorrectly packaged requiring manual install (and pretty much all of these would have failed with Vortex - which is why I did this). Only 1 was incorrectly identified as packaged correctly when it wasn't. This was because the mod had a zip file in it and MO2 presented only the contents of this inner zip file to my code.

**Pull request merged**
