### PR TITLE
added very basic Nier:Automata support

### PR DESCRIPTION
**Pull request by EzioTheDeadPoet**

### CODE REVIEW

**Comment by LostDragonist** [comment]
Initial report from Timbo says there's some kind of problem running the game with MO.  Possibly some kind of DRM interfering with USVFS.  Further testing is needed before this gets merged in.

**Comment by Holt59** [comment]
@LostDragonist Any news on this?

**Comment by EzioTheDeadPoet** [comment]
iirc Testing has went stale, since Tombo went to mod Nier:Automata manually and my PC can't run it sadly.
But in August I would be up to some new tests. I am not home rn so it would be harder to test now.

**Comment by LostDragonist** [comment]
Finally got around to trying this.  It passed a basic test with the opening credit videos so /shrug.

**Pull request merged**
