### PR TITLE
changed binary to non steam specific one

### PR DESCRIPTION
**Pull request by EzioTheDeadPoet**

### CODE REVIEW

**Comment by Holt59** [comment]
That's a bit more complex than that. The game binary is used to detect if the folder is valid, so you probably to change a bit more than just the list of executables.

**Comment by EzioTheDeadPoet** [comment]
The steam version and the GOG version come with that folder and therefore it should work with both, and the EGS version of the game only has that binary. Therefore I would assume that the check if the folder is valid should still work. I can be wrong tho, but I had multiple sources mentioning that the GOG and Steam version have this executable and I know it from the EGS version 1st hand.

**Comment by Holt59** [comment]
DD is on sale so I'm going to try the Steam version as soon as Steam let me buy it (the payment process is broken right now... ).

**Comment by EzioTheDeadPoet** [comment]
My assumption would be that it will not register reached steam achievements with the `_windowsnosteam\\Darkest` due to that .exe probably misses the steamcode,

**Comment by EzioTheDeadPoet** [comment]
Someone tested with the steam version, on the latest release build of MO2 (not the DEV build), and besides the autodetection failing the edit worked to identify the folder as a valid folder. And I tested with a manual selection of the EGS folder and it worked as well.

**Comment by Holt59** [comment]
Thanks, I've tested (finally managed to buy the game... ), and the auto-detection works (actually it's based on the Steam library + registry so the executable is not really important).

I would use the Steam executable if present in `executables` because I'd expect this if I bought the game on Steam. You can do a simple check for the presence of the Steam version and fallback to the no-Steam if it's not present.

**Comment by EzioTheDeadPoet** [comment]
I have totally forgotten how I would do that but I will look into it in a while. 

So if I would add the steam one into the `executables` before the `nonsteam` one it would list them in that order and skip the steam one if it doesn't find it. ? or would I need to make a specific exception to catch the steam one not existing ?

**Comment by Holt59** [comment]
I would only keep one, even if both exists. Something like this should be sufficient:

```python
def executables(self):
    path = QFileInfo(self.gameDirectory(), "_windows/darkest.exe")
    if not path.exists():
        path = QFileInfo(self.gameDirectory(), "_windowsnosteam/darkest.exe")
    return [
        mobase.ExecutableInfo("Darkest Dungeon", path),
    ]
```

**Pull request merged**
