### PR TITLE
Cyberpunk full support

### PR DESCRIPTION
**Pull request by ZashIn**
Current state and workarounds (to be integrated) are described in the [wiki page for Cyberpunk 2077](/ModOrganizer2/modorganizer-basic_games/wiki/Game:-Cyberpunk-2077)

## Features
Implemented features in this plugin update
- [x] profile specific config (`.ini`)
- [x] profile specific savegames, based on #122
- [x] savegame preview & metadata, based on #109
- [x] Auto mod installation (ModDataChecker): see table below
  - [x] RedMod: auto deployment before game launch, with load order from MO
- [x] Auto framework installation
  - [x] redscript
  - [x] RED4ext & CET: get moved into `root` to be either copied manually into game install dir or automatic via [RootBuilder](https://kezyma.github.io/?p=rootbuilder)
- ~Sync mod settings back to mods (some are currently saved to overwrite, since config files get created after game launch)~
- [x] Enforce MOs load for `.archive` (`archive/pc/mod/modlist.txt`) and REDmod (`-modlist`)
- [x] RootBuilder config: working default config set automatically (once)

## Mod support
Here is an overview of the mod / framework support as of MO 2.5 beta 14 (Cyberpunk game plugin v2.1) and the compatibility with MOs virtual file system USVFS:
<table>
    <thead>
        <tr>
            <th colspan="2"></th>
            <th colspan="2"> Support: mods&nbsp;/&nbsp;framework </th>
        </tr>
        <tr>
            <th>Mod type / framework</th>
            <th>Mod folder (files)</th>
            <th>Auto install*</th>
            <th>USVFS</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>archive</td>
            <td><code>archvie/...</code> <code>(.archive)</code></td>
            <td>✔️/ &ndash;</td>
            <td>✔️/ &ndash;</td>
        </tr>
        <tr>
            <td><a href="https://www.nexusmods.com/cyberpunk2077/mods/1511">redscript</a></td>
            <td><code>r6/...</code> <code>(.reds)</code></td>
            <td>✔️/✔️</td>
            <td>✔️/✔️</td>
        </tr>
        <tr>
            <td><a href="https://www.nexusmods.com/cyberpunk2077/mods/2380">RED4ext</a></td>
            <td><code>red4ext/...</code> <code>(.dll)</code></td>
            <td>✔️/✔️<sup><a href="#f-root">root</a></sup></td>
            <td>✔️/❌*</td>
        </tr>
        <tr>
            <td><a href="https://www.nexusmods.com/cyberpunk2077/mods/107">Cyber Engine Tweaks (CET)</a></td>
            <td><code>bin/x64/plugins/...</code> <code>(.lua)</code></td>
            <td>✔️/✔️<sup><a href="#f-root">root</a></sup></td>
            <td>✔️&nbsp;1.27 / ❌*</td>
        </tr>
        <tr>
            <td><a href="https://www.cyberpunk.net/en/modding-support">REDMod</a></td>
            <td><code>mods/*</code> <code>(info.json, ...)</code></td>
            <td>✔️/❌(DLC)</td>
            <td>✔️/❌(DLC)</td>
        </tr>
    </tbody>
</table>

<b id="f-root">root:</b> Auto install only into (virtual) `root` folder, compatible with  [RootBuilder](https://kezyma.github.io/?p=rootbuilder) (copy/hardlink). Alternative: copy manually into game dir.

\* Remarks
- [RED4ext](https://www.nexusmods.com/cyberpunk2077/mods/2380): Only the framework (2 `.dll` files) need to be copied / hard linked to `root`, dependent mods work with USVFS then.
- [Cyber Engine Tweaks (CET)](https://www.nexusmods.com/cyberpunk2077/mods/107):
  - Cyberpunk v2.01, CET &ge;1.27: only CET framework needs to be copies / hard linked into `root` (all files), mods work with USVFS.
  - Cyberpunk v1.x, CET &le;1.26: is not compatible with USVFS, see [CET issue / PR](/maximegmd/CyberEngineTweaks/pull/877) for details.
- [RedMod](https://www.cyberpunk.net/en/modding-support): precompilation is now supported
- [RootBuilder](https://kezyma.github.io/?p=rootbuilder) can be used to automate hard linking / coping `root` files into game dir (only frameworks RED4ext and CET, no mods)

Tested with:
- Cyberpunk 2077 v2.01
- MO v2.5.0 beta 12+
- RootBuilder 4.4 (copy mode) and 4.5 (hard link mode)

Related issues:
- Fixes ModOrganizer2/modorganizer#1742
- Fixes ModOrganizer2/modorganizer#1719
- Fixes ModOrganizer2/modorganizer#1487

### CODE REVIEW

**Comment by ZashIn** [comment]
I have repurposed this PR to the full Cyberpunk support update (WIP), since I forgot to split the the commits into a separate branch after the initial fix (first commit) for the ini files errror.
Added status update in the first comment.

**Comment by ZashIn** [comment]
With hard links only mode from the upcoming RootBuilder update (https://github.com/Kezyma/ModOrganizer-Plugins/pull/13) everything should work, except Redmods (still needs manual precompilation).
Although this basically disables UVFS completely and use only hard links as a workaround.

**Comment by Holt59** [comment]
I'm not sure I want to include in basic games a game plugin that heavily depends on a third-party plugin. Maybe the best option here would be to make your third-party plugin for Cyberpunk. Note that you should still be able to use basic games feature, you simply need to change the relative imports.

**Comment by ZashIn** [comment]
CET v1.27 for Cyberpunk 2.01 added a [compatibility fix for USVFS](https://github.com/maximegmd/CyberEngineTweaks/pull/877), which requires only the frameworks CET and Red4ext to be copied / hard linked into game root.
So except for Redmod, all mods should work with USVFS.

Will update the PR after some testing.

**Comment by ZashIn** [comment]
Updated to work with CET v1.27 (Cyberpunk 2.01).
I removed the RootBuilder config and incomplete redmod handling for now.
Based on #122 and #109, so they should be merged first.

**Comment by ZashIn** [comment]
Added REDmod support with auto precompilation in MOs load order.
Still not quite sure about best RootBuilder config (or whether to include one at all). See also Kezyma/ModOrganizer-Plugins#18

**Comment by ZashIn** [comment]
If RootBuilder is installed, compatible default settings are now applied.
[The minor RootBuilder bug](/Kezyma/ModOrganizer-Plugins/issues/18) with hard link mode is (more or less) already fixed in latest release 4.5.2, Even without the fix, everything works, just some file conflicts with duplicated framework files in overwrite can show up after REDmod precompilation.
Copy mode works and is fallback for earlier versions anyways.

From my end this plugin update is now complete and can be merged.

**Comment by ZashIn** [comment]
PR ready for merge.

**Comment by Lhyris** [comment]
Giving your plugin a try, but a small annoyance is that supplementary files, such as .png files, will throw off the move= part of the GlobPatterns. So far I've tried this with [Wingdeer's Hair Collection](https://www.nexusmods.com/cyberpunk2077/mods/6072) mod, but any .zip that contains more than just the .archive, will require manual adjusting during installation. Could you look into this please? :)

**Comment by ZashIn** [comment]
@Lhyris can you test this fix, accepting basically all extra files: [cyberpunk-v2.2.2](https://github.com/ZashIn/modorganizer-basic_games/releases/tag/cyberpunk-v2.2.2)

**Comment by death0serpent** [comment]
Is there any guide that will help me successfully set up MO2 for CP2077 step-by-step?!

**Comment by ZashIn** [comment]
The [Cyberpunk wiki](https://github.com/ModOrganizer2/modorganizer-basic_games/wiki/Game:-Cyberpunk-2077) is up to date, although a bit technical.
But the basic setup is quite easy: you just need to install the requirements CET and RED4ext either manually into game folder or via RootBuilder (install the MO2 extension, then you can just add CET and RED4ext as normal mods within MO2).
It only can get complicated with for load order etc., but I tried to cover that in the wiki.

**Pull request merged**
